// this_file: src/wordlist.h
// AUTO-GENERATED by scripts/generate_data.py. Do not edit.
#pragma once
#include <QStringList>
#include <QVector>
#include <QPair>
#include <QChar>

namespace namzy {
const QStringList& stems();
const QVector<QPair<QChar, QChar>>& rotations();
}
