// this_file: src/wordlist.h
// AUTO-GENERATED by scripts/generate_data.py. Do not edit.
#pragma once
#include <QStringList>
#include <QVector>
#include <QPair>
#include <QString>

namespace namzy {
const QStringList& stems();
const QVector<QPair<QString, QString>>& rotations();
const QStringList& badSeams();
}
