#!/usr/bin/env python3
"""Synchronize namzy package versions across all implementations."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SEMVER_RE = re.compile(r"^v?(\d+)\.(\d+)\.(\d+)(?:[-+][0-9A-Za-z.-]+)?$")


def normalize_version(raw: str) -> tuple[str, str]:
    version = raw.strip()
    match = SEMVER_RE.match(version)
    if not match:
        raise SystemExit(f"Expected a semver string like v1.2.3, got: {raw!r}")
    bare = version[1:] if version.startswith("v") else version
    return bare, f"v{bare}"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8")


def replace_once(text: str, pattern: str, repl: str, path: Path) -> str:
    new, count = re.subn(pattern, repl, text, count=1, flags=re.MULTILINE)
    if count != 1:
        raise SystemExit(f"Could not update {path}: pattern not found: {pattern}")
    return new


def update_json(path: Path, mutator) -> None:
    data = json.loads(read_text(path))
    mutator(data)
    write_text(path, json.dumps(data, indent=2, ensure_ascii=False) + "\n")


def update_ts(version: str) -> None:
    package_json = ROOT / "namzy-ts" / "package.json"
    package_lock = ROOT / "namzy-ts" / "package-lock.json"

    def mutate_package(data: dict) -> None:
        data["version"] = version
        data.setdefault("bin", {})["namzy"] = "dist/cli.js"

    def mutate_lock(data: dict) -> None:
        data["version"] = version
        root = data.setdefault("packages", {}).setdefault("", {})
        root["version"] = version
        root.setdefault("bin", {})["namzy"] = "dist/cli.js"

    update_json(package_json, mutate_package)
    update_json(package_lock, mutate_lock)


def update_python(version: str) -> None:
    pyproject = ROOT / "namzy-py" / "pyproject.toml"
    version_file = ROOT / "namzy-py" / "src" / "namzy" / "__version__.py"
    init_file = ROOT / "namzy-py" / "src" / "namzy" / "__init__.py"

    text = read_text(pyproject)
    if re.search(r'^version = ', text, flags=re.MULTILINE):
        text = replace_once(text, r'^version = ".*"$', 'dynamic = ["version"]', pyproject)
    elif 'dynamic = ["version"]' not in text:
        raise SystemExit(f"Could not find project version or dynamic version in {pyproject}")
    text = replace_once(
        text,
        r'^path = "src/namzy/.*"$',
        'path = "src/namzy/__version__.py"',
        pyproject,
    )
    write_text(pyproject, text)

    write_text(
        version_file,
        f'"""Generated by scripts/sync_version.py. Do not edit."""\n\n__version__ = "{version}"\n',
    )

    init_text = read_text(init_file)
    init_text = re.sub(r'^__version__ = ".*"\n\n', '', init_text, count=1, flags=re.MULTILINE)
    if "from .__version__ import __version__" not in init_text:
        marker = "from ._wordlist import COMMON, GEO\n"
        replacement = (
            "from ._wordlist import COMMON, GEO\n\n"
            "try:\n"
            "    from .__version__ import __version__\n"
            "except ModuleNotFoundError:\n"
            "    __version__ = \"0+unknown\"\n"
        )
        if marker not in init_text:
            raise SystemExit(f"Could not insert __version__ import in {init_file}")
        init_text = init_text.replace(marker, replacement, 1)
    init_text = init_text.replace('__all__ = ["generate"]', '__all__ = ["generate", "__version__"]')
    write_text(init_file, init_text)


def update_rust(version: str) -> None:
    cargo_toml = ROOT / "namzy-rs" / "Cargo.toml"
    text = read_text(cargo_toml)
    text = replace_once(text, r'^version = ".*"$', f'version = "{version}"', cargo_toml)
    write_text(cargo_toml, text)


def update_cpp(version: str) -> None:
    cmake = ROOT / "namzy-cpp" / "CMakeLists.txt"
    main_cpp = ROOT / "namzy-cpp" / "src" / "main.cpp"

    cmake_text = read_text(cmake)
    cmake_text = replace_once(
        cmake_text,
        r'^project\(namzy VERSION [^ ]+ LANGUAGES CXX\)$',
        f'project(namzy VERSION {version} LANGUAGES CXX)',
        cmake,
    )
    if "target_compile_definitions" not in cmake_text:
        cmake_text = cmake_text.rstrip() + '\n\ntarget_compile_definitions(namzy PRIVATE NAMZY_VERSION="${PROJECT_VERSION}")\n'
    write_text(cmake, cmake_text)

    main_text = read_text(main_cpp)
    if "app.setApplicationVersion(QStringLiteral(NAMZY_VERSION));" not in main_text:
        main_text = replace_once(
            main_text,
            r'app\.setApplicationVersion\(QStringLiteral\(".*"\)\);',
            'app.setApplicationVersion(QStringLiteral(NAMZY_VERSION));',
            main_cpp,
        )
    write_text(main_cpp, main_text)


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        raise SystemExit("Usage: scripts/sync_version.py <vX.Y.Z|X.Y.Z>")
    version, tag = normalize_version(argv[1])
    update_ts(version)
    update_python(version)
    update_rust(version)
    update_cpp(version)
    print(f"Synchronized package versions to {version} ({tag})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
